// React-PDF templates — server-side only (used in /api/documents route)
// Do NOT import this file from client components.
import React from 'react'
import {
  Document,
  Page,
  View,
  Text,
  StyleSheet,
} from '@react-pdf/renderer'
import type { DocumentType } from '@/types'

// ── Shared styles ────────────────────────────────────────────────
const S = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10.5,
    lineHeight: 1.6,
    color: '#1A1A1A',
    paddingTop: 48,
    paddingBottom: 60,
    paddingHorizontal: 56,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: '#2C5530',
  },
  brandBlock: { flexDirection: 'column' },
  brandName: { fontSize: 16, fontFamily: 'Helvetica-Bold', color: '#2C5530' },
  brandSub: { fontSize: 8, color: '#6B7280' },
  docMeta: { fontSize: 8, color: '#6B7280', textAlign: 'right' },
  title: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    textAlign: 'center',
    textTransform: 'uppercase',
    marginTop: 18,
    marginBottom: 14,
    letterSpacing: 1,
  },
  section: { marginBottom: 10 },
  label: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: '#6B7280', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 2 },
  value: { fontSize: 10.5 },
  paragraph: { marginBottom: 8, textAlign: 'justify' },
  divider: { borderBottomWidth: 0.5, borderBottomColor: '#D1D5DB', marginVertical: 10 },
  signatureBlock: { marginTop: 32, flexDirection: 'row', justifyContent: 'space-between' },
  sigLine: { width: 180 },
  sigLineText: { fontSize: 9, color: '#6B7280', borderTopWidth: 0.5, borderTopColor: '#9CA3AF', paddingTop: 4 },
  footer: { position: 'absolute', bottom: 24, left: 56, right: 56, textAlign: 'center', fontSize: 7.5, color: '#9CA3AF', borderTopWidth: 0.5, borderTopColor: '#E5E7EB', paddingTop: 4 },
  numbered: { flexDirection: 'row', marginBottom: 6 },
  numberedN: { width: 20, fontSize: 10.5, fontFamily: 'Helvetica-Bold' },
  numberedText: { flex: 1, fontSize: 10.5 },
  row: { flexDirection: 'row', gap: 16, marginBottom: 10 },
  col: { flex: 1 },
  tableRow: { flexDirection: 'row', borderBottomWidth: 0.5, borderBottomColor: '#E5E7EB', paddingVertical: 5 },
  tableLbl: { width: 160, fontSize: 9, fontFamily: 'Helvetica-Bold', color: '#6B7280' },
  tableVal: { flex: 1, fontSize: 9 },
})

// ── Shared header ────────────────────────────────────────────────
function DocHeader({ title, date }: { title: string; date?: string }) {
  return (
    <>
      <View style={S.header}>
        <View style={S.brandBlock}>
          <Text style={S.brandName}>NYAAY</Text>
          <Text style={S.brandSub}>Indian Legal Assistant · nyaay.app</Text>
        </View>
        <View>
          <Text style={S.docMeta}>Generated by NYAAY</Text>
          {date && <Text style={S.docMeta}>{date}</Text>}
        </View>
      </View>
      <Text style={S.title}>{title}</Text>
    </>
  )
}

// ── Shared footer ────────────────────────────────────────────────
function DocFooter() {
  return (
    <View style={S.footer} fixed>
      <Text>This document is generated for reference. Consult a qualified advocate before use. NYAAY provides legal information, not legal advice.</Text>
    </View>
  )
}

// ── Field helper ────────────────────────────────────────────────
function Field({ label, value }: { label: string; value?: string }) {
  return (
    <View style={S.tableRow}>
      <Text style={S.tableLbl}>{label}</Text>
      <Text style={S.tableVal}>{value ?? '—'}</Text>
    </View>
  )
}

// ────────────────────────────────────────────────────────────────
// LEGAL NOTICE
// ────────────────────────────────────────────────────────────────
interface LegalNoticeData {
  sender_name?: string; sender_address?: string; sender_phone?: string
  recipient_name?: string; recipient_address?: string
  subject?: string; details?: string; relief_sought?: string
  deadline_days?: string; notice_date?: string
}

function LegalNotice({ data }: { data: LegalNoticeData }) {
  const deadlineDays = data.deadline_days ?? '15'
  return (
    <Document>
      <Page size="A4" style={S.page}>
        <DocHeader title="Legal Notice" date={data.notice_date} />

        <View style={[S.section, { marginBottom: 14 }]}>
          <Text style={S.label}>From</Text>
          <Text style={S.value}>{data.sender_name}</Text>
          <Text style={S.value}>{data.sender_address}</Text>
          <Text style={S.value}>Ph: {data.sender_phone}</Text>
        </View>

        <View style={[S.section, { marginBottom: 14 }]}>
          <Text style={S.label}>To</Text>
          <Text style={S.value}>{data.recipient_name}</Text>
          <Text style={S.value}>{data.recipient_address}</Text>
        </View>

        <View style={S.divider} />

        <Text style={S.paragraph}>
          <Text style={{ fontFamily: 'Helvetica-Bold' }}>Subject: </Text>
          {data.subject}
        </Text>

        <Text style={S.paragraph}>
          Dear {data.recipient_name},{'\n\n'}
          Under instructions from and on behalf of my client <Text style={{ fontFamily: 'Helvetica-Bold' }}>{data.sender_name}</Text>, I hereby serve upon you this legal notice as follows:
        </Text>

        <Text style={[S.label, { marginBottom: 4 }]}>Background & Grievance</Text>
        <Text style={S.paragraph}>{data.details}</Text>

        <Text style={[S.label, { marginBottom: 4 }]}>Relief / Demand</Text>
        <Text style={S.paragraph}>{data.relief_sought}</Text>

        <Text style={S.paragraph}>
          You are hereby called upon to comply with the above demand within <Text style={{ fontFamily: 'Helvetica-Bold' }}>{deadlineDays} days</Text> from the receipt of this notice, failing which my client reserves the right to initiate appropriate legal proceedings against you without further notice, entirely at your cost and risk.
        </Text>

        <View style={S.signatureBlock}>
          <View style={S.sigLine}>
            <Text style={S.sigLineText}>Sender's Signature</Text>
          </View>
          <View style={S.sigLine}>
            <Text style={S.sigLineText}>Date: {data.notice_date}</Text>
          </View>
        </View>

        <DocFooter />
      </Page>
    </Document>
  )
}

// ────────────────────────────────────────────────────────────────
// RTI APPLICATION
// ────────────────────────────────────────────────────────────────
interface RTIData {
  applicant_name?: string; applicant_address?: string; applicant_phone?: string
  department?: string; pio_designation?: string
  information_sought?: string; period?: string
  fee_mode?: string; application_date?: string
}

function RTIApplication({ data }: { data: RTIData }) {
  return (
    <Document>
      <Page size="A4" style={S.page}>
        <DocHeader title="Application under Right to Information Act, 2005" date={data.application_date} />

        <Text style={S.paragraph}>
          <Text style={{ fontFamily: 'Helvetica-Bold' }}>To,{'\n'}</Text>
          The Public Information Officer{data.pio_designation ? ` (${data.pio_designation})` : ''},{'\n'}
          {data.department}
        </Text>

        <View style={S.divider} />

        <Text style={[S.label, { marginBottom: 6 }]}>Applicant Details</Text>
        <Field label="Name" value={data.applicant_name} />
        <Field label="Address" value={data.applicant_address} />
        <Field label="Phone / Email" value={data.applicant_phone} />
        <Field label="Fee Payment" value={data.fee_mode} />

        <View style={S.divider} />

        <Text style={[S.label, { marginBottom: 4 }]}>Information Sought</Text>
        {data.period && (
          <Text style={[S.paragraph, { fontSize: 9, color: '#6B7280' }]}>
            Period: {data.period}
          </Text>
        )}
        <Text style={S.paragraph}>{data.information_sought}</Text>

        <View style={S.divider} />

        <Text style={S.paragraph}>
          I state that the information sought does not fall within the restrictions contained in Section 8 and 9 of the RTI Act, 2005. A fee of ₹10 is enclosed herewith as prescribed.
        </Text>

        <View style={S.signatureBlock}>
          <View style={S.sigLine}>
            <Text style={S.sigLineText}>Applicant's Signature</Text>
          </View>
          <View style={S.sigLine}>
            <Text style={S.sigLineText}>Date: {data.application_date}</Text>
          </View>
        </View>

        <DocFooter />
      </Page>
    </Document>
  )
}

// ────────────────────────────────────────────────────────────────
// POLICE COMPLAINT
// ────────────────────────────────────────────────────────────────
interface PoliceComplaintData {
  complainant_name?: string; complainant_address?: string; complainant_phone?: string
  police_station?: string; accused_name?: string
  incident_date?: string; incident_place?: string
  description?: string; witnesses?: string; complaint_date?: string
}

function PoliceComplaint({ data }: { data: PoliceComplaintData }) {
  return (
    <Document>
      <Page size="A4" style={S.page}>
        <DocHeader title="Complaint / FIR Application" date={data.complaint_date} />

        <Text style={S.paragraph}>
          <Text style={{ fontFamily: 'Helvetica-Bold' }}>To,{'\n'}</Text>
          The Officer-in-Charge,{'\n'}
          {data.police_station} Police Station
        </Text>

        <View style={S.divider} />

        <Text style={[S.label, { marginBottom: 6 }]}>Complainant Details</Text>
        <Field label="Name" value={data.complainant_name} />
        <Field label="Address" value={data.complainant_address} />
        <Field label="Phone" value={data.complainant_phone} />

        <View style={S.divider} />

        <Text style={[S.label, { marginBottom: 6 }]}>Incident Details</Text>
        <Field label="Date of Incident" value={data.incident_date} />
        <Field label="Place of Incident" value={data.incident_place} />
        {data.accused_name && <Field label="Accused Name" value={data.accused_name} />}

        <View style={S.divider} />

        <Text style={[S.label, { marginBottom: 4 }]}>Description</Text>
        <Text style={S.paragraph}>{data.description}</Text>

        {data.witnesses && (
          <>
            <Text style={[S.label, { marginBottom: 4 }]}>Witnesses</Text>
            <Text style={S.paragraph}>{data.witnesses}</Text>
          </>
        )}

        <Text style={S.paragraph}>
          I, {data.complainant_name}, hereby request you to register my complaint and take appropriate legal action against the accused person(s) under relevant sections of the Bharatiya Nyaya Sanhita, 2023.
        </Text>

        <View style={S.signatureBlock}>
          <View style={S.sigLine}>
            <Text style={S.sigLineText}>Complainant's Signature</Text>
          </View>
          <View style={S.sigLine}>
            <Text style={S.sigLineText}>Date: {data.complaint_date}</Text>
          </View>
        </View>

        <DocFooter />
      </Page>
    </Document>
  )
}

// ────────────────────────────────────────────────────────────────
// CONSUMER COMPLAINT
// ────────────────────────────────────────────────────────────────
interface ConsumerComplaintData {
  complainant_name?: string; complainant_address?: string; complainant_phone?: string
  company_name?: string; company_address?: string
  product_service?: string; purchase_date?: string; amount_paid?: string
  complaint_details?: string; relief_sought?: string; complaint_date?: string
}

function ConsumerComplaint({ data }: { data: ConsumerComplaintData }) {
  return (
    <Document>
      <Page size="A4" style={S.page}>
        <DocHeader title="Consumer Complaint — Consumer Protection Act, 2019" date={data.complaint_date} />

        <View style={S.row}>
          <View style={S.col}>
            <Text style={S.label}>Complainant</Text>
            <Text style={S.value}>{data.complainant_name}</Text>
            <Text style={S.value}>{data.complainant_address}</Text>
            <Text style={S.value}>{data.complainant_phone}</Text>
          </View>
          <View style={S.col}>
            <Text style={S.label}>Opposite Party</Text>
            <Text style={S.value}>{data.company_name}</Text>
            <Text style={S.value}>{data.company_address}</Text>
          </View>
        </View>

        <View style={S.divider} />

        <Text style={[S.label, { marginBottom: 6 }]}>Transaction Details</Text>
        <Field label="Product / Service" value={data.product_service} />
        <Field label="Date of Purchase" value={data.purchase_date} />
        <Field label="Amount Paid" value={data.amount_paid ? `₹${data.amount_paid}` : undefined} />

        <View style={S.divider} />

        <Text style={[S.label, { marginBottom: 4 }]}>Complaint</Text>
        <Text style={S.paragraph}>{data.complaint_details}</Text>

        <Text style={[S.label, { marginBottom: 4 }]}>Relief Sought</Text>
        <Text style={S.paragraph}>{data.relief_sought}</Text>

        <Text style={S.paragraph}>
          I declare that the above complaint is correct and true to the best of my knowledge and belief. I pray that this Hon'ble Forum may be pleased to grant the above reliefs in the interest of justice.
        </Text>

        <View style={S.signatureBlock}>
          <View style={S.sigLine}>
            <Text style={S.sigLineText}>Complainant's Signature</Text>
          </View>
          <View style={S.sigLine}>
            <Text style={S.sigLineText}>Date: {data.complaint_date}</Text>
          </View>
        </View>

        <DocFooter />
      </Page>
    </Document>
  )
}

// ────────────────────────────────────────────────────────────────
// AFFIDAVIT
// ────────────────────────────────────────────────────────────────
interface AffidavitData {
  deponent_name?: string; father_name?: string; age?: string; address?: string
  purpose?: string; statement?: string; place?: string; affidavit_date?: string
}

function Affidavit({ data }: { data: AffidavitData }) {
  return (
    <Document>
      <Page size="A4" style={S.page}>
        <DocHeader title="Affidavit" date={data.affidavit_date} />

        <Text style={S.paragraph}>
          I, <Text style={{ fontFamily: 'Helvetica-Bold' }}>{data.deponent_name}</Text>, aged {data.age} years, son/daughter/wife of {data.father_name}, residing at {data.address}, do hereby solemnly affirm and declare as under:
        </Text>

        <View style={S.divider} />

        <Text style={[S.label, { marginBottom: 4 }]}>Purpose</Text>
        <Text style={S.paragraph}>{data.purpose}</Text>

        <Text style={[S.label, { marginBottom: 4 }]}>Sworn Statement</Text>
        <Text style={S.paragraph}>{data.statement}</Text>

        <View style={S.divider} />

        <Text style={S.paragraph}>
          I state that the contents of this affidavit are true and correct to the best of my knowledge and belief. Nothing has been concealed or misrepresented herein.
        </Text>

        <Text style={S.paragraph}>
          Verified at <Text style={{ fontFamily: 'Helvetica-Bold' }}>{data.place}</Text> on this day of <Text style={{ fontFamily: 'Helvetica-Bold' }}>{data.affidavit_date}</Text>.
        </Text>

        <View style={S.signatureBlock}>
          <View style={S.sigLine}>
            <Text style={S.sigLineText}>Deponent's Signature</Text>
          </View>
          <View style={S.sigLine}>
            <Text style={S.sigLineText}>Before me — Notary / Magistrate</Text>
          </View>
        </View>

        <DocFooter />
      </Page>
    </Document>
  )
}

// ────────────────────────────────────────────────────────────────
// RENT AGREEMENT
// ────────────────────────────────────────────────────────────────
interface RentAgreementData {
  landlord_name?: string; landlord_address?: string; landlord_phone?: string
  tenant_name?: string; tenant_address?: string; tenant_phone?: string
  property_address?: string; monthly_rent?: string; security_deposit?: string
  start_date?: string; duration_months?: string; lock_in_months?: string
  notice_days?: string; agreement_date?: string
}

function RentAgreement({ data }: { data: RentAgreementData }) {
  const duration = data.duration_months ?? '11'
  const lockIn = data.lock_in_months ?? '6'
  const notice = data.notice_days ?? '30'

  return (
    <Document>
      <Page size="A4" style={S.page}>
        <DocHeader title="Residential Rental Agreement" date={data.agreement_date} />

        <Text style={S.paragraph}>
          This Rental Agreement is entered into on <Text style={{ fontFamily: 'Helvetica-Bold' }}>{data.agreement_date}</Text> between:
        </Text>

        <View style={S.row}>
          <View style={S.col}>
            <Text style={S.label}>Landlord (Lessor)</Text>
            <Text style={S.value}>{data.landlord_name}</Text>
            <Text style={S.value}>{data.landlord_address}</Text>
            <Text style={S.value}>Ph: {data.landlord_phone}</Text>
          </View>
          <View style={S.col}>
            <Text style={S.label}>Tenant (Lessee)</Text>
            <Text style={S.value}>{data.tenant_name}</Text>
            <Text style={S.value}>{data.tenant_address}</Text>
            <Text style={S.value}>Ph: {data.tenant_phone}</Text>
          </View>
        </View>

        <View style={S.divider} />

        <Text style={[S.label, { marginBottom: 6 }]}>Property & Terms</Text>
        <Field label="Property Address" value={data.property_address} />
        <Field label="Monthly Rent" value={data.monthly_rent ? `₹${data.monthly_rent}` : undefined} />
        <Field label="Security Deposit" value={data.security_deposit ? `₹${data.security_deposit}` : undefined} />
        <Field label="Lease Start Date" value={data.start_date} />
        <Field label="Lease Duration" value={`${duration} months`} />
        <Field label="Lock-in Period" value={`${lockIn} months`} />
        <Field label="Notice Period" value={`${notice} days`} />

        <View style={S.divider} />

        <Text style={[S.label, { marginBottom: 4 }]}>Terms & Conditions</Text>
        {[
          `The Tenant shall pay rent of ₹${data.monthly_rent ?? '—'} on or before the 5th of every month.`,
          `A security deposit of ₹${data.security_deposit ?? '—'} is paid by the Tenant, refundable on vacating the premises after deduction of dues.`,
          `The Tenant shall not sub-let or transfer the premises without prior written consent of the Landlord.`,
          `Either party may terminate this agreement after the lock-in period by giving ${notice} days' written notice.`,
          `The Tenant shall maintain the premises in good condition and bear minor repairs. Major repairs are the Landlord's responsibility.`,
          `This agreement is subject to applicable state Rent Control laws.`,
        ].map((clause, i) => (
          <View key={i} style={S.numbered}>
            <Text style={S.numberedN}>{i + 1}.</Text>
            <Text style={S.numberedText}>{clause}</Text>
          </View>
        ))}

        <View style={[S.signatureBlock, { marginTop: 24 }]}>
          <View style={S.sigLine}>
            <Text style={S.sigLineText}>Landlord's Signature</Text>
          </View>
          <View style={S.sigLine}>
            <Text style={S.sigLineText}>Tenant's Signature</Text>
          </View>
        </View>

        <DocFooter />
      </Page>
    </Document>
  )
}

// ── Template dispatcher ──────────────────────────────────────────
export function getDocumentTemplate(
  type: DocumentType,
  data: Record<string, string>
): React.ReactElement {
  switch (type) {
    case 'LEGAL_NOTICE':       return <LegalNotice data={data} />
    case 'RTI_APPLICATION':    return <RTIApplication data={data} />
    case 'POLICE_COMPLAINT':   return <PoliceComplaint data={data} />
    case 'CONSUMER_COMPLAINT': return <ConsumerComplaint data={data} />
    case 'AFFIDAVIT':          return <Affidavit data={data} />
    case 'RENT_AGREEMENT':     return <RentAgreement data={data} />
  }
}
